#include <curses.h>
#include <sys/ioctl.h>
#include "../main.h"

void printTitle(){
    int width;
    int height;
    struct winsize wbuf;
    if(ioctl(0, TIOCGWINSZ, &wbuf) != - COLOR_PAIR_WHITE){
        width = wbuf.ws_col;
        height = wbuf.ws_row;
    }

    int x = width/COLOR_PAIR_RED-40;
    int y = height/4;
    
    wbkgd(stdscr, COLOR_PAIR(4));

    move(y + 0, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED));
    for(int i = 0; i < 80; i ++)printw(" ");

    move(y + 1, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("                                     ");

    move(y + 2, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("   ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("   ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("                                     ");

    move(y + 3, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("                                     ");

    move(y + 4, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("                                      ");

    move(y + 5, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("       ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("   ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("                                     ");

    move(y + 6, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED));
    for(int i = 0; i < 80; i ++)printw(" ");

    move(y + 7, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("          ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("    ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("      ");
 
    move(y + 8, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("    ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("          ");

    move(y + 9, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("    ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("      ");

    move(y + 10, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw(" ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("   ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("    ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw(" ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("   ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("      ");

    move(y + 11, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("    ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("      ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_WHITE)); printw("  ");
    attron(COLOR_PAIR(COLOR_PAIR_RED)); printw("  ");

    move(y + 12, x);
    attron(COLOR_PAIR(COLOR_PAIR_RED));
    for(int i = 0; i < 80; i ++)printw(" ");
    refresh();
}